version: '3.8'

services:
  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - 6000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwt-authentication
    command:
      [
        'mysqld',
        '--default-authentication-plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
      ]
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
